### ISSUE TITLE
New main background image

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip_elo#1]
The theme comes with a sample background image. @elmcip suggested we replace this with one of Bergen and supplied a image taken from Ulriken.
### Before

![electronic_literature_organization_conference___elo_conference_-__private_browsing_](https://cloud.githubusercontent.com/assets/683617/6130447/75f2c5e0-b145-11e4-8e39-fc54ec1b500d.png)
### After

![electronic_literature_organization_conference___elo_conference_-__private_browsing_](https://cloud.githubusercontent.com/assets/683617/6130432/693ec146-b145-11e4-9cfb-39fd46e86461.png)

I also created this issue to keep the ball rolling on getting this theme and site config and ready for production.

**Comment by steinmb** [comment]
Commit: 59591a4 add this though you should discuss if it OK or it should be changed with another one.

**Comment by steinmb** [comment]
@AlvaroSeica for the sake of order.

To locally test it out. Got the theme folder:
- "git pull" 
- refresh elo.dev.

To look at the page before the the change do: 
- git checkout 758128b
- refresh elo.dev

To revert back to latest
- git checkout master
- refresh elo.dev

**Comment by AlvaroSeica** [comment]
@steinmb yes but the cmdl to get into the theme folder is: elmcip ase053$ cd Users/Shared/elmcip_config/elmcip/elmcip_elo can't get it...
also, the background of the inner theme is white now on the live site

**Comment by steinmb** [comment]
Have no idea where you got that path from. It is as you prob. have guessed is it 100% wrong :)

```
cd /Users/Shared/elmcip_config/html/sites/all/themes/elmcip_elo
```

Is perhaps right. 
If not have a look inside the folder /Users/Shared/elmcip_config for the right name. Your config is not the same as mine so you need no document this for your self.

**Comment by AlvaroSeica** [comment]
@steinmb tks! ok locally tested the commit and the master and it is working. :)
@elmcip it seems better with the Ulriken panorama, though @steinmb you need to commit as well the white background in the inside skin as it is now running on the live site

**Comment by steinmb** [comment]
Remember that the live site is running a unmodified theme. Aka these are simply theme settings found in admin. Try to tweak your theme setting http://elo.dev/admin/appearance/settings/elmcip_elo pick a light color scheme to match the live site (if that is the scheme we are going for @elmcip ?)

**Comment by steinmb** [comment]
Think this is OK now
