### ISSUE TITLE
Conference site wish list

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip_elo#2]
Let's have a general dumping place for ideas and stuff that should be addressed. Consider this a meta-issue where everything goes. If stuff turn out to be bigger jobs we just spin off a separate issue for them.
## Wish list
- [ ] #4 Improve drop down menus. Feel a little counter intuitive at the moment.
- [ ] More beer?

**Comment by steinmb** [comment]
@AlvaroSeica invited

**Comment by AlvaroSeica** [comment]
@elmcip what's next?
