### ISSUE TITLE
Create region to store conference logos

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip_elo#3]
The conference have multiple partners and supporters. These logos need to live one the site pages.

**Comment by steinmb** [comment]
@elmcip and @AlvaroSeica do a `git pull` and have a look. I have added multiple, identical, logos to simulate logos overflowing page width.

**Comment by AlvaroSeica** [comment]
@steinmb changed the page.tpl.php with new code, but some logos have square resolutions and don't fit so well when rescaled to 60 x 60 pixels. can you check this?

**Comment by steinmb** [comment]
Looks OK
