### ISSUE TITLE
Logos in footer hyperlinks is missing

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip_elo#7]
Logos in footer hyperlinks still contain the anchor link # instead of the real http://example.com for each partner.
## fix

Replace all "#" with "http://url-to-partner-site" in page.tpl.php footer region.

**Comment by AlvaroSeica** [comment]
@steinmb OK I'll do this!

**Comment by AlvaroSeica** [comment]
@steinmb @elmcip all logos hyperlinked now and updated version of elmcip_elo.sql uploaded to the shared ELMCIP folder now
