### ISSUE TITLE
Lydgalleriet logo missing

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip_elo#8]
On front page, Lydgalleriet logo did not make it into to update. @AlvaroSeica can you push that up?

**Comment by steinmb** [comment]
Are you sure about that? It's in there and commit cda0f4491962782b6f35f9f77de57ff7c7ff77ff did add it.

**Comment by steinmb** [comment]
Filename case issue. Fixed in e03f3206635b2cf95deb88ff23b5f85eb49dfc86
