### ISSUE TITLE
All logos missing on pages other than front

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip_elo#9]
@steinmb This looks awful. Any ideas why?

https://www.dropbox.com/s/wsqz5y38fie9n8z/Screenshot%202015-04-16%2020.23.08.png?dl=0

**Comment by steinmb** [comment]
Nothing to do with the installation it self. Prob. have something to do about how the site have been located/the directory structure of the filesystem. Here is an example of how the directories are accessed. Nothing is hard coded. There 

`<img src="<?php print $theme_path; ?>/images/FRlogoEngrgb-farger.png"

So if this site lives in a VirtualDocumentRoot RewriteBase must be altered in (example) .htaccess.

**Comment by elmcip** [comment]
Appears to all be part of issue 10 closing.

**Comment by AlvaroSeica** [comment]
It's fine in the live site

## 

�lvaro Sei�a

PhD fellow
Digital Culture + Electronic Literature Research Group
University of Bergen
http://elmcip.net/person/alvaro-seica

Sent from my iPhone12 supermegatron

On 16 Apr 2015, at 23:02, Scott Rettberg <notifications@github.com<mailto:notifications@github.com>> wrote:

Appears to all be part of issue 10 closing.

�
